### PR TITLE
Allow it to work under Xvfb.

### PR DESCRIPTION
**Pull request by notriddle**
Part of servo/servo#8641

### CODE REVIEW

**Comment by tomaka** [comment]
I'm hesitating. It's definitely not a good change, as it ignores errors on purpose, but on the other hand fullscreen support is so crappy that it needs a rewrite anyway.

**Comment by notriddle** [comment]
Any way to get into full screen mode without using that extension? We could
use that as a fallback instead...

**Comment by tomaka** [comment]
I'll just merge this.

**Pull request merged**
