### PR TITLE
Implement set_cursor_position on OSX with Cocoa

### PR DESCRIPTION
**Pull request by AnthIste**
The implementation uses [CGWarpMouseCursorPosition](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/Quartz_Services_Ref/index.html#//apple_ref/c/func/CGWarpMouseCursorPosition) that accepts global screen coordinates. These are therefore offset by the current window coordinates.

### CODE REVIEW

**Comment by fkaa** [comment]
Looks good to me. Have you noticed any delay as mentioned in the original issue? Also seems to fix #664

**Comment by AnthIste** [comment]
I haven't personally noticed any delay, but I haven't done extensive testing. I see on [this stackoverflow answer](http://stackoverflow.com/a/17559012/761648) a workaround is to call `CGAssociateMouseAndMouseCursorPosition(true)` immediately after warping the cursor. [This post](https://groups.google.com/forum/#!msg/wx-dev/dkKkq2v929U/XoOMu4yPniUJ) also suggests that it is a valid (if undocumented) fix.

I'll update the code to include this and test locally. I can't tell if it fixes any delay because I am not experiencing any, but I will be able to see if it causes problems.

**Comment by AnthIste** [comment]
Adding in the extra call actually made a huge difference in cursor responsiveness :)

I based this change on the current stable crates.io version but I think it should be OK to merge into master. When is the next crates.io release scheduled? I need this functionality so I am currently referencing my own local bugfix version.

**Comment by tomaka** [comment]
@AnthIste Just submit a PR which bumps the version in the Cargo.toml

**Pull request merged**
