### PR TITLE
Add a way to retrieve the EGL display

### PR DESCRIPTION
**Pull request by ceyusa**
to say EGLDisplay ~or XDisplay~

### CODE REVIEW

**Comment by jdm** [comment]
@francesca64 Are you the right person to review these changes?

**Comment by jdm** [comment]
Note: this is addressing #1078.

**Comment by francesca64** [comment]
@jdm I'm the right person, but there are currently a few other things I need to review, so it can be hard to find time.

@ceyusa thanks for the PR!

`Window::native_display` follows the style of the `platform_display` and `platform_window` methods that were deprecated in glutin/winit a while ago, and were recently removed. The convention we've moved to is using `WindowExt` methods per-platform, each with their own documentation and descriptive name (`native_display` isn't really an acceptable name, simply because it's so similar to the name of a method that was recently removed).

I'm also not a fan of having external types exposed, since it means that dependency upgrades could be breaking changes. We use void pointers (`*mut std::os::raw::c_void`) to get around this issue (see #939 for discussion).

Having macOS and iOS return `0` isn't idiomatic, and is very surprising/dangerous. My recommendation is to just create `WindowExt` methods (probably `get_egl_display`) for the platforms that can have an `EGLDisplay`. You can use an `Option`, and document on Windows that `None` indicates WGL, and on X11 that `None` indicates GLX (in which case, the `XDisplay` can be retrieved via [`WindowExt::get_xlib_display`](https://github.com/tomaka/winit/blob/aabf0e13b78e156aac3037c9051f49534195e489/src/os/unix.rs#L99); also including a note that Wayland always uses EGL).

**Comment by ceyusa** [comment]
Thanks a lot for the review! :)

> My recommendation is to just create `WindowExt` methods (probably `get_egl_display`) for the platforms that can have an `EGLDisplay`.

If I understand correctly, this method should be in in `winit`, not int `glutin`. Do I understand correctly?

**Comment by ceyusa** [comment]
> Do I understand correctly?

Nope. I did not :) there's no EGL code in winit...

**Comment by ceyusa** [comment]
Sorry, I'm lost. I'm staring at the code and the only way that I see is creating a `GlContextExt` trait with the `get_egl_display()` method, implemented by the platform's GlContext.

Otherwise, I should add the method in `winit`'s trait and implement them in `glutin`, which looks odd to me.

**Comment by francesca64** [comment]
Right, sorry. I think `GlContextExt` makes sense for this.

**Comment by ceyusa** [comment]
\o/ all checks passed

@francesca64 whenever you can :)

**Comment by francesca64** [comment]
Sorry for the delay! This looks good to me, but it would be great if you could add a CHANGELOG entry. Then we'll be good to merge.

**Comment by ceyusa** [comment]
> Sorry for the delay! This looks good to me, but it would be great if you could add a CHANGELOG entry. Then we'll be good to merge.

Done :)

**Pull request merged**
