### PR TITLE
Update code example in README.md

### PR DESCRIPTION
**Pull request by wschella**
The example was not representative of the current API.

### CODE REVIEW

**Comment by ZeGentzy** [comment]
This example is representative of the upcoming 0.20 api, however I do understand the confusion, so I'll merge this now and revert it before release. Thanks.

**Comment by wschella** [comment]
Ah I understand my troubles now. No need to keep this in then, it might be confusing for those building from git now :wink:

**Comment by ZeGentzy** [comment]
@wschella Is this non-confusing? https://github.com/tomaka/glutin/blob/068fb05f3f195358c0e0a1de0a494448bd37738f/README.md

**Comment by wschella** [comment]
@ZeGentzy Ah yes! A sweet little reminder that GitHub doesn't reflect the version people are probably using.

**Pull request merged**
