### PR TITLE
Bump winit and glutin

### PR DESCRIPTION
**Pull request by stuartnelson3**
Use the latest release of winit and bump glutin

### CODE REVIEW

**Comment by tomaka** [comment]
Glutin 0.11 uses winit 0.8.

**Comment by stuartnelson3** [comment]
I'm confused, it seems like it's glutin 0.10 that's using winit 0.8? What should the versions be?

**Comment by tomaka** [comment]
Oh ignore my comment, I thought I was in a different repo.

**Comment by stuartnelson3** [comment]
no problem. fixed the failing example.

**Pull request merged**
