### PR TITLE
add Touch events for win32

### PR DESCRIPTION
**Pull request by cpardotortosa**

### CODE REVIEW

**Comment by tomaka** [comment]
The structs, functions and constants should use the winapi crate, not be defined directly in glutin.

**Comment by cpardotortosa** [comment]
I only defined those that are not yet defined on winapi. I could add them to winapi first.

**Comment by retep998** [comment]
Feel free to submit a PR to winapi with the things you need.

**Comment by cpardotortosa** [comment]
Required changes are already on winapi. I need to wait for a crates.io release, don't I?

**Comment by retep998** [comment]
Probably yeah.

**Pull request closed without merging**
