### PR TITLE
Add the `windows-static-egl` Cargo feature

### LINKED ISSUE #997: Support statically-linked libEGL? (On Windows)
https://github.com/servo/mozangle compiles ANGLE, on Windows with an EGL implementation. To avoid the complication of shipping `.dll` files separately, it is linked as a static library.

Glutin supports EGL on Windows, but loads it from a dynamic library like `libEGL.dll`. What do you think of adding support for statically-linked EGL?

Conditionally having something like `extern { fn eglGetProcAddress(…) }` directly in Glutin would require a compile-time flag, which isn’t great. So maybe that function could be (optionally) provided by users:

```rust
impl<'a> ContextBuilder<'a> {
    pub fn with_egl_get_proc_address<F>(mut self, get_proc_address: F) -> Self
        where F: Fn(&str) -> *const c_void
    {
        self.egl_get_proc_address = Some(Box::new(get_proc_address))
        self
    }
}
```

Since this is only relevant on Windows, maybe it should be in a `glutin::os::windows::ContextBuilderExt` trait.

Or maybe something more automagic could be made with weak symbols, but those don’t seem to be available in Stable Rust.

Thoughts?

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes #997: this allows using Glutin together with https://crates.io/crates/mozangle

### CODE REVIEW

**Comment by SimonSapin** [comment]
Should mozangle be mentioned in the doc as a possible way to use this feature?

Should mozangle be added as in `dev-dependencies` and the program below added under `examples/`?

```rust
#[cfg(not(windows))]
fn main() {
    println!("This example only runs on Windows.");
}

#[cfg(windows)] extern crate mozangle;
#[cfg(windows)] extern crate glutin;

#[cfg(windows)]
fn main() {
    use glutin::GlContext;
    use glutin::os::GlContextExt;
    use glutin::os::windows::RawHandle;
    use mozangle::egl::get_proc_address;
    use mozangle::gles::ffi as gl;

    let mut events_loop = glutin::EventsLoop::new();
    let window = glutin::WindowBuilder::new();
    let context = glutin::ContextBuilder::new()
        // Requesting OpenGlEs is required to make glutin try to use EGL.
        .with_gl(glutin::GlRequest::Specific(glutin::Api::OpenGlEs, (2, 0)));
    let gl_window = glutin::GlWindow::new(window, context, &events_loop).unwrap();

    let handle = unsafe {
        gl_window.context().raw_handle()
    };
    match handle {
        RawHandle::Egl(_) => {},
        RawHandle::Wgl(_) => panic!("Expected an EGL context, found a WGL one.")
    }

    assert_ne!(gl_window.get_proc_address("glClearColor"), 0 as _);
    assert_eq!(gl_window.get_proc_address("glClearColor"), get_proc_address("glClearColor") as _);

    unsafe {
        gl_window.make_current().unwrap();
        gl::ClearColor(0., 0.5, 0., 1.);
    }

    events_loop.run_forever(|event| {
        match event {
            glutin::Event::WindowEvent { event, .. } => match event {
                glutin::WindowEvent::Closed => return glutin::ControlFlow::Break,
                glutin::WindowEvent::Resized(w, h) => gl_window.resize(w, h),
                _ => (),
            },
            _ => ()
        }

        unsafe {
            gl::Clear(gl::COLOR_BUFFER_BIT);
        }

        gl_window.swap_buffers().unwrap();
        glutin::ControlFlow::Continue
    });
}
```

**Comment by SimonSapin** [comment]
The example program in the previous comment is subject to https://github.com/tomaka/winit/issues/415. (Maybe Clear + swap_buffers is slow in debug mode? And re-rendering on non-resize events is unnecessary.)

**Comment by tomaka** [comment]
I'm not fan of this feature but I guess I will merge anyway.

Please solve the conflict, and also please remove the example because for such a niche feature I don't think an example really makes sense.

**Comment by SimonSapin** [comment]
I’m not really a fan of it either. I think it’s preferable for WebRender/Wrench to use winit + EGL instead of this.

**Pull request closed without merging**
