### PR TITLE
git submodule was never commited

### PR DESCRIPTION
**Pull request by oli-obk**
the .gitmodules file was updated, but if the actual submodule isn't commited, `git submodule init` does nothing.

found the solution through stackoverflow: http://stackoverflow.com/a/9049703/1103681

### CODE REVIEW

**Comment by tomaka** [comment]
Ah in fact it's the contrary. I forgot to remove `.gitmodules`.

**Comment by oli-obk** [comment]
so the android tutorial at https://github.com/tomaka/glutin#android is outdated?

**Comment by tomaka** [comment]
What is described still works.

However it doesn't really make sense to teach how to compile glutin itself for Android. You should learn how to compile your own project for android, and know that glutin supports Android.

**Comment by oli-obk** [comment]
> You should learn how to compile your own project for android, and know that glutin supports Android.

Yea ^^ working on that...

**Pull request closed without merging**
