### PR TITLE
win fix: min/max dimensions now correctly use client area size

### LINKED ISSUE #681: resizability & min/max dimensions
There didn't seem to be a resizable flag so I tried setting the min and max dimension to the same values as the window dimensions. This didn't seem to give the desired effect. 
with_min_dimensions() & with_max_dimensions() set the dimension _including_ the window border. I don't think this is the desired behavior for most users. 

platform: windows 7

```
    let window = glutin::WindowBuilder::new()
        .with_title("Title".to_string())
        .with_dimensions(720, 480) // set the size excluding the border
        .with_min_dimensions(720, 480) // sets the size including the border
        .with_max_dimensions(720, 480) // sets the size including the border
        .build_glium()
        .unwrap();

```

### PR DESCRIPTION
**Pull request by SenneH**
Fixed #681.

### CODE REVIEW

**Comment by Sergesosio** [comment]
I also fixed the issue in #355.

**Comment by tomaka** [comment]
Thanks!

However issue #355 is already being fixed by PR #682.

Also, since you added the `resizable` flag, please add an `assert!(window.resizable);` in `api/glx/window.rs`, `api/android` and `api/cocoa`.

**Comment by Sergesosio** [comment]
#682 doesn't fix #355. It only adds functionality to change the cursor icon to another. The issue about the cursor not changing into to resize icon when hovering the border of the window is still there. 
I could make it so that it correctly uses the default behavior if no cursor is set?

**Comment by tomaka** [comment]
Looks good!

However why do you need to add a `reset_cursor` function instead of just setting the value to `None` if the user calls `set_cursor(Default)`?

Also you need to add `assert!(window.resizable);` before I merge.

**Comment by Sergesosio** [comment]
You're right, having a ```resert_cursor``` function is unnecessary. ```set_cursor``` should now accept an ```Option<>```

As for ```assert!(window.resizable);```, I added it in ```api/android``` and ```api/cocoa```. But I don't have the file ```api/glx/window.rs```

**Comment by tomaka** [comment]
I meant `api/x11/window.rs` instead of `glx`.

For the cursor, please don't change it to an `Option`. There a `MouseCursor::Default` variant that is supposed to mean "the default cursor".

**Comment by francesca64** [comment]
It looks like `resizable` is the only part of this that would still be relevant, and I doubt it would be worth the effort to try to rebase this for winit.

**Comment by francesca64** [comment]
and now `resizable` is being covered over in tomaka/winit#540

**Pull request closed without merging**
