### PR TITLE
Fix EGL for wayland.

### PR DESCRIPTION
**Pull request by vberger**
These are the changes I managed to get EGL context initialization to work on wayland on my computer.

I don't really know what all that implies, it was mostly try and retry.

Your thoughts @tomaka ?

### CODE REVIEW

**Comment by tomaka** [comment]
Do you get an error with `EGL_SURFACE_TYPE`?

**Comment by vberger** [comment]
If I don't comment out the `SURFACE_TYPE` block, `eglChooseConfig` triggers a `EGL_BAD_ATTRIBUTE`.

No idea what's causing this, maybe a bug in my version of Mesa? Could be nice if someone else coult test as well.

**Comment by tomaka** [comment]
Well, I noticed an error in that `SURFACE_TYPE`, `PBUFFER_BIT` and `WINDOW_BIT` are supported even by EGL 1.0. So that `if` could be removed.

**Comment by tomaka** [comment]
@vberger What happens if you leave only `WINDOW_BIT`?

**Comment by vberger** [comment]
@tomaka cannot test it right now, will do it later in the afternoon.

However, if I remember correctly what I read in the EGL spec, having only `WINDOW_BIT` is the default value for this attribute.

**Comment by tomaka** [comment]
> having only WINDOW_BIT is the default value for this attribute.

That's why I'm asking what happens.

**Comment by vberger** [comment]
By removing `PBUFFER_BIT` it works as well.

**Comment by tomaka** [comment]
Please add a comment in the code explaining the situation, then I'll merge.

**Pull request merged**
