### PR TITLE
Lock objc to 0.1.7. Fix remaining libc pointer errors with casts. Fix warnings in cursor example.

### LINKED ISSUE #654: Compilation error on OS X 10.11.1 with rust 1.4
With stable rust I get the following error in a glium project:

```
± % cargo run                                                                              23:37:08
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling glutin v0.4.1
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:146:18: 146:62 error: the trait `objc::encode::Encode` is not implemented for the type `*mut libc::types::common::c95::c_void` [E0277]
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:146             decl.add_ivar::<*mut libc::c_void>("glutinState");
                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:146:18: 146:62 help: run `rustc --explain E0277` to see a detailed explanation
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:163:31: 163:86 error: the trait `objc::encode::Encode` is not implemented for the type `*mut libc::types::common::c95::c_void` [E0277]
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:163             (&mut **delegate).set_ivar("glutinState", state_ptr as *mut libc::c_void);
                                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:163:31: 163:86 help: run `rustc --explain E0277` to see a detailed explanation
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:84:54: 84:77 error: the trait `objc::encode::Encode` is not implemented for the type `*mut libc::types::common::c95::c_void` [E0277]
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:84                 let state: *mut libc::c_void = *this.get_ivar("glutinState");
                                                                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:84:54: 84:77 help: run `rustc --explain E0277` to see a detailed explanation
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:93:54: 93:77 error: the trait `objc::encode::Encode` is not implemented for the type `*mut libc::types::common::c95::c_void` [E0277]
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:93                 let state: *mut libc::c_void = *this.get_ivar("glutinState");
                                                                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:93:54: 93:77 help: run `rustc --explain E0277` to see a detailed explanation
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:112:54: 112:77 error: the trait `objc::encode::Encode` is not implemented for the type `*mut libc::types::common::c95::c_void` [E0277]
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:112                 let state: *mut libc::c_void = *this.get_ivar("glutinState");
                                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:112:54: 112:77 help: run `rustc --explain E0277` to see a detailed explanation
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:120:54: 120:77 error: the trait `objc::encode::Encode` is not implemented for the type `*mut libc::types::common::c95::c_void` [E0277]
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:120                 let state: *mut libc::c_void = *this.get_ivar("glutinState");
                                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:120:54: 120:77 help: run `rustc --explain E0277` to see a detailed explanation
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:313:33: 313:36 error: mismatched types:
 expected `*mut libc::types::common::c95::c_void`,
    found `*mut libc::c_void`
(expected enum `libc::types::common::c95::c_void`,
    found enum `libc::c_void`) [E0308]
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:313                 CGLSetParameter(obj, kCGLCPSurfaceOpacity, &mut opacity);
                                                                                                                                  ^~~
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:313:33: 313:36 help: run `rustc --explain E0308` to see a detailed explanation
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:561:31: 561:50 error: mismatched types:
 expected `*mut libc::types::common::c95::c_void`,
    found `*mut libc::c_void`
(expected enum `libc::types::common::c95::c_void`,
    found enum `libc::c_void`) [E0308]
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:561                     CGLEnable(cxt.CGLContextObj(), kCGLCECrashOnRemovedFunctions);
                                                                                                                                ^~~~~~~~~~~~~~~~~~~
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:526:17: 566:18 note: in this expansion of if let expansion
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:521:13: 569:14 note: in this expansion of if let expansion
/Users/paul/.cargo/registry/src/github.com-0a35038f75765ae4/glutin-0.4.1/src/api/cocoa/mod.rs:561:31: 561:50 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 8 previous errors
Could not compile `glutin`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by mitchmindtree**
This fixes #654

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Build was successful on nightly osx, stable linux and two of the windows builds. Each of the others seem to have either timed out due to cargo hanging on an update or crashed in some unrelated process :tada:

**Comment by mitchmindtree** [comment]
Ahhhh, despite this change working for glutin, users will likely still run into problems downstream as the cocoa crate also depends on objc, in turn creating an objc version conflict. For example, when I try to build conrod (with the local working glutin version) I get:

```
failed to select a version for `objc` (required by `glutin`):
all possible versions conflict with previously selected versions of `objc`
  version 0.1.8 in use by objc v0.1.8
  possible versions to select: 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
```
Which doesn't seem to get fixed no matter how many times I `cargo update` or `cargo clean`.

**Comment by SSheldon** [comment]
@mitchmindtree, sorry again that the objc update has contributed to this mess :/

It's not the most elegant, but one way to sidestep this issue would be to replace all uses of `*mut libc::c_void` with `usize`, like:
``` diff
diff --git a/src/api/cocoa/mod.rs b/src/api/cocoa/mod.rs
index 2b4b5e5..1e5000b 100644
--- a/src/api/cocoa/mod.rs
+++ b/src/api/cocoa/mod.rs
@@ -81,7 +81,7 @@ impl WindowDelegate {
 
         extern fn window_should_close(this: &Object, _: Sel, _: id) -> BOOL {
             unsafe {
-                let state: *mut libc::c_void = *this.get_ivar("glutinState");
+                let state: usize = *this.get_ivar("glutinState");
                 let state = state as *mut DelegateState;
                 (*state).pending_events.lock().unwrap().push_back(Closed);
             }
@@ -90,7 +90,7 @@ impl WindowDelegate {
 
         extern fn window_did_resize(this: &Object, _: Sel, _: id) {
             unsafe {
-                let state: *mut libc::c_void = *this.get_ivar("glutinState");
+                let state: usize = *this.get_ivar("glutinState");
                 let state = &mut *(state as *mut DelegateState);
 
                 let _: () = msg_send![*state.context, update];
@@ -109,7 +109,7 @@ impl WindowDelegate {
                 // TODO: center the cursor if the window had mouse grab when it
                 // lost focus
 
-                let state: *mut libc::c_void = *this.get_ivar("glutinState");
+                let state: usize = *this.get_ivar("glutinState");
                 let state = state as *mut DelegateState;
                 (*state).pending_events.lock().unwrap().push_back(Focused(true));
             }
@@ -117,7 +117,7 @@ impl WindowDelegate {
 
         extern fn window_did_resign_key(this: &Object, _: Sel, _: id) {
             unsafe {
-                let state: *mut libc::c_void = *this.get_ivar("glutinState");
+                let state: usize = *this.get_ivar("glutinState");
                 let state = state as *mut DelegateState;
                 (*state).pending_events.lock().unwrap().push_back(Focused(false));
             }
@@ -143,7 +143,7 @@ impl WindowDelegate {
                 window_did_resign_key as extern fn(&Object, Sel, id));
 
             // Store internal state as user data
-            decl.add_ivar::<*mut libc::c_void>("glutinState");
+            decl.add_ivar::<usize>("glutinState");
 
             delegate_class = decl.register();
         });
@@ -160,7 +160,7 @@ impl WindowDelegate {
         unsafe {
             let delegate = IdRef::new(msg_send![WindowDelegate::class(), new]);
 
-            (&mut **delegate).set_ivar("glutinState", state_ptr as *mut libc::c_void);
+            (&mut **delegate).set_ivar("glutinState", state_ptr as usize);
             let _: () = msg_send![*state.window, setDelegate:*delegate];
 
             WindowDelegate { state: state, _this: delegate }
```

That way a mismatch between the libc versions in glutin and objc doesn't cause any errors.

**Comment by tomaka** [comment]
Or just use `*mut ()` instead of `usize`.

**Comment by SSheldon** [comment]
I'm not sure `*mut ()` will work, it needs to be a type for which an Objective-C type encoding is known.

`*mut _` also doesn't seem to work, since then the type is unconstrained; these methods can take any type, not just `*mut c_void`.

**Comment by mitchmindtree** [comment]
@SSheldon all good! It can be easy to overlook breakages sometimes especially when it's just in a version increment heh.

I tried building this again locally, however a wild #656 appeared. I don't have a windows system available to me atm so I'm unable to address this.

I did however try just updating `kernel32-sys` to `0.2` to appease the issue locally, however I was unable to see if this fixed anything as I'm now stuck behind rust-lang/cargo#2090, as is travis it seems. :confused:

**Comment by tomaka** [comment]
Ok, let's merge this.

**Pull request merged**
