### PR TITLE
Removed the setBestResolutionOpenGLSurface option

### PR DESCRIPTION
**Pull request by DavidPartouche**
That should fix the issue @TyOverby had in https://github.com/tomaka/glutin/pull/128

### CODE REVIEW

**Comment by glennw** [comment]
@tomaka @DavidPartouche Could we get this change merged? It appears to fix the size of the retina screen and I have a separate PR coming shortly which fixes the mouse events on mac.

**Comment by glennw** [comment]
@tomaka @DavidPartouche Actually, scratch that. It looks like removing this just means you get a low resolution surface that is upscaled. I'll investigate a better way to support it.

**Comment by glennw** [comment]
I have merged the changes to support retina displays, suggest we close this one.

**Comment by TyOverby** [comment]
@glennw: where are these merged changes?  I tried to find them but couldn't.

**Comment by glennw** [comment]
@TyOverby https://github.com/tomaka/glutin/pull/211

**Comment by bjz** [comment]
Closing as requested.

**Pull request closed without merging**
