### PR TITLE
Add support for navigation keys

### PR DESCRIPTION
**Pull request by Manishearth**
These are becoming more and more common on new keyboards (especially on lenovo laptops)

### CODE REVIEW

**Comment by Manishearth** [comment]
I couldn't figure out the cocoa key code, though.

**Comment by Manishearth** [comment]
Turns out the linux one doesn't work, "Prior" just means "PageUp". The actual key names are "XF86Forward" and "XF86Back" (keycode 166, 167)

**Comment by Manishearth** [comment]
The keycode is 0x1008ff26/0x1008ff27 on linux. Filed https://github.com/Daggerbot/x11-rs/issues/34

**Comment by Manishearth** [comment]
https://github.com/Daggerbot/x11-rs/commit/e877a899c5f032e2870f29578ead25c0b0913845 landed

**Comment by tomaka** [comment]
Travis still fails. I think you need to bump the x11 version.

**Comment by Manishearth** [comment]
Yeah, I'm waitinfg for x11 to get bumped

**Comment by Manishearth** [comment]
Done

**Comment by Manishearth** [comment]
Build passes. I tested it locally on linux, too, it works.

**Pull request merged**
