### PR TITLE
Update to android_glue 0.2

### PR DESCRIPTION
**Pull request by ozkriff**
https://github.com/tomaka/android-rs-glue/issues/93

### CODE REVIEW

**Comment by tomaka** [comment]
The small blocker here is Servo. I don't think they want to change their complex Android build system immediately.

cc @glennw @larsbergstrom

**Comment by larsbergstrom** [comment]
If it's just changes to the types in the glue code, that should hopefully be fine to land.

The only change we're thinking about to our current Android build system in Servo is to move from the  deprecated `ndk-build` / `ant` system to `gradle`, which is the more modern way of building them. The new 'cargo apk' command is awesome, but I'm pretty sure that if we tried to accommodate all of Servo's manifest, java, resources, icon, etc. requirements plus the stuff needed to support finicky ndk-gdb issues, the nvidia profiler, etc., we'd end up in a similar situation to where we are with glutin where Servo is pulling in a very different direction from the needs of every other user in the community.

**Comment by ozkriff** [comment]
> manifest, java, resources, icon, etc. requirements plus the stuff needed to support finicky ndk-gdb issues, the nvidia profiler, etc.

Hmm, why cargo-apk doesn`t need that? As for me, sounds like useful features for many native android apps.

**Comment by ozkriff** [comment]
Ping? :)

**Comment by tomaka** [comment]
@larsbergstrom @glennw If you don't disagree, I'm going to merge this PR. When you update your fork from upstream glutin, you should add a commit that reverts it.

**Comment by ozkriff** [comment]
crates.io version in still not updated :(

**Pull request merged**
