### PR TITLE
Setup deployment on crates.io

### PR DESCRIPTION
**Pull request by tomaka**
Automatically deploy a version on crates.io stripped down from OS/X and Android

### CODE REVIEW

**Comment by TyOverby** [comment]
Don't you also need to increment the version number?

**Comment by tomaka** [comment]
I've modified `0.0.4-pre` to `0.0.4` in this PR. The version `0.0.4` has been uploaded.

**Comment by TyOverby** [comment]
Doesn't this change make it so that it will auto-publish?

**Comment by tomaka** [comment]
Yes, it will autopublish as soon as I change the version number in the Cargo.toml

**Comment by TyOverby** [comment]
Oh, I see.  So you make the version number change manually, and then it automatically publishes?

**Comment by tomaka** [comment]
Yes

**Pull request merged**
