### PR TITLE
Update gl_generator to 0.9 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by paulrouget** [comment]
Please add an entry in the CHANGELOG.

**Comment by paulrouget** [comment]
@tomaka said: "we don't need a changelog entry for things not exposed in the API"

**Comment by tomaka** [comment]
Yanking. Will publish 0.13 instead.

**Comment by Eijebong** [comment]
@tomaka Did that include any breaking change ? Or did you have breaking changes waiting on master ?

**Pull request merged**
