### PR TITLE
RC3

### PR DESCRIPTION
**Pull request by ZeGentzy**
https://github.com/servo/servo/issues/23189

Signed-off-by: Hal Gentz <zegentzy@protonmail.com>

### CODE REVIEW

**Comment by atouchet** [comment]
Could you also bump x11-dl to 2.18.3 in glutin_glx_sys? I think that accidentally got downgraded when it was moved into the sys crate.

**Comment by ZeGentzy** [comment]
Afaik, it's already been updated in 0.1.3.

Downgrading wayland-client, forgot we aren't on evlpv2 yet.

**Comment by atouchet** [comment]
It says it's set to 2.18 only. Last I checked versions prior to 2.18.3 had issues compiling with new versions of Rust.

**Comment by ZeGentzy** [comment]
It says `^0.28`, and my Cargo.lock has this:
```
[[package]]
name = "glutin_glx_sys"
version = "0.1.4"
dependencies = [
 "gl_generator 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "x11-dl 2.18.3 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

Maybe run `cargo update` once rc3 is out?

**Pull request merged**
