### PR TITLE
x11: Improve xlib error reporting

### PR DESCRIPTION
**Pull request by ecoal95**
This will show the X error string when an error happens, which should help to diagnose errors.

I re-opened `xlib` since:

 * This is not expected to be called a lot, so performance should not matter *that much*.
 * I didn't know what the best way to restructure of the current code will be.

I'll be happy to re-organize it if you wish.

### CODE REVIEW

**Comment by vberger** [comment]
Calling `unwrap()` in `extern "C"` code is generally a bad idea, as panicking into C code is undefined behavior.

Probably matching the result of `Xlib::open()` and falling back to the old error message if it failed would be a better setup, even if `Xlib::open()` here is very unlikely to fail.

**Comment by ecoal95** [comment]
I unwrapped there since it since a failure there was *really* unlikely to happen (it had been successfully opened previously).

Agreed though, it's easy to prevent. I updated the PR accordingly :)

**Comment by tomaka** [comment]
From experience I have noticed that the `XGetErrorText` function is beyond useless. For example if you call it with the error code 52, it will return something like `"error 52"`.
I remember trying various error codes just to see if the function was working at all, and **all** error codes returned `"error #n"`.

**Comment by ecoal95** [comment]
In my case it does report something kind of useful.

For example, on my machine with this patch `cargo run --example=multiwindow` yields:

```
$ cargo run --example=multiwindow
[glutin] x error code=8 major=42 minor=0: BadMatch (invalid parameter attributes)!
OpenGL version 3.3 (Core Profile) Mesa 11.2.0-devel (git-8cc372b 2015-12-10 wily-oibaf-ppa)
OpenGL version 3.3 (Core Profile) Mesa 11.2.0-devel (git-8cc372b 2015-12-10 wily-oibaf-ppa)
OpenGL version 3.3 (Core Profile) Mesa 11.2.0-devel (git-8cc372b 2015-12-10 wily-oibaf-ppa)
```

(I'm investigating what causes that error too)

**Comment by ecoal95** [comment]
The errors I see are on `SetInputFocus`, so they're not dangerous I think (it just fails to switch the windows focus), am I right?.

**Comment by tomaka** [comment]
I think that the fact that you reopen xlib is too hacky to be merged.
A better solution, I think, would be to move the callback function to [api_dispatch.rs](https://github.com/tomaka/glutin/blob/master/src/platform/linux/api_dispatch.rs) and read the existing xlib from the `BACKEND` variable.
The point to the callback function would then be passed as a parameter to `XConnection::new`.

**Comment by ecoal95** [comment]
Agreed, just did it.

**Comment by tomaka** [comment]
Thanks!

I'll leave this open in case someone has something to say about this design.
Otherwise I'll merge in ~24 hours. Please ping me if I forget.

**Pull request merged**
