### PR TITLE
x11, android, win: [ui]size -> [ui]32

### PR DESCRIPTION
**Pull request by ozkriff**

### CODE REVIEW

**Comment by ozkriff** [comment]
NOTE: have not tested win32, only made it pass appveyor.

**Comment by ozkriff** [comment]
By the way, do we really need u32? May be replace it with i32 (+ few "assert!(n>=0)") for consistency?

**Comment by tomaka** [comment]
I think I prefer separating u32 and i32.

**Comment by ozkriff** [comment]
ok :)

**Comment by ozkriff** [comment]
r?

**Pull request merged**
