### PR TITLE
Add phases to wheel events.

### PR DESCRIPTION
**Pull request by pcwalton**
Needed for apps to support overscroll on the Mac.

r? @paulrouget

### CODE REVIEW

**Comment by paulrouget** [comment]
`TouchPhase` not imported everywhere (at least windows, don't know about linux).

**Comment by tomaka** [comment]
Even more bloating :'(

**Comment by metajack** [comment]
@tomaka Not sure what you mean by bloat. Aren't users of the library going to want to use all the events at their disposal?

**Comment by metajack** [comment]
Superceded by #735

**Comment by tomaka** [comment]
@metajack The major problem here is that it's totally undocumented.
Also this commit broke Emscripten and Android, and probably iOS.
Also this commit is a breaking change and will require bumping the major version.

When I started glutin I wanted to write clean code, and in the last month or so this has been a total failure.

**Comment by metajack** [comment]
Sorry I would have addressed those in the updated patch had I known or had it failed tests. We can certainly do a better job of adding documentation in the future.

On the bright side, this has enabled some great features in Browser.html / Servo.

**Pull request closed without merging**
