### PR TITLE
Update to winit 0.15.0 + release glutin 0.16.0

### PR DESCRIPTION
**Pull request by francesca64**

### CODE REVIEW

**Comment by francesca64** [comment]
Well, I hope to release winit 0.15.0 in a few days, so there's not really a point in merging this yet. (winit 0.15.0 will basically be a glorified patch release with a very minor breaking API change.)

**Comment by Rhuagh** [comment]
When is the release planned?

**Comment by francesca64** [comment]
winit 0.15.0 has already been released, and included in this PR. It's just a matter of locking the @tomaka mutex, since I've not been blessed with write permissions on glutin.

**Comment by francesca64** [comment]
Update: the prayers worked, so I'm able to merge this now!

**Pull request merged**
