### PR TITLE
Fix the winapi build again

### PR DESCRIPTION
**Pull request by tomaka**
I'm sticking to specific versions and will update manually from time to time.

cc @retep998

### CODE REVIEW

**Comment by tomaka** [comment]
https://github.com/rust-lang/cargo/issues/1815

**Comment by retep998** [comment]
Sorry :disappointed:

**Comment by tomaka** [comment]
This PR can't work because of the Cargo bug.
Even if the Cargo bug is fixed, I'd have to wait until a new version is released. So I'm closing this.

**Comment by tomaka** [comment]
But I'm still interested in knowing the result of CI to know if the cargo bug is fixed.
I'll close afterwards.

**Pull request closed without merging**
