### PR TITLE
Allow any winit >=0.8.1 to track the 0.8 series automatically

### PR DESCRIPTION
**Pull request by pedrocr**

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Wouldn't this mean that if a user depends on glutin and winit publishes some breaking changes (in a 0.9 release for example) that the user's code would possibly break as a result? I think I'd prefer if we kept updating one version at a time to avoid downstream breakages.

**Comment by pedrocr** [comment]
Ah, you're right, I should have done a different condition. Just a sec

**Comment by pedrocr** [comment]
This should now allow `>=0.8.1 && <0.9.0` if I've read the docs correctly here:

http://doc.crates.io/specifying-dependencies.html#caret-requirements

**Comment by vberger** [comment]
Note that the cargo documentation states that the version requirement `"a.b.c"` is interpreted as `"^a.b.c"`, so this PR does not change cargo behavior (though it makes the dependency more explicit).

**Comment by pedrocr** [comment]
No need for this then, closing

**Pull request closed without merging**
