### PR TITLE
Implement some more Cocoa stuff

### PR DESCRIPTION
**Pull request by bjz**

### CODE REVIEW

**Comment by tomaka** [comment]
Yay the rename \o/

For `get_position`, it's supposed to be the distance between the top-left hand corner of the screen and the top-left hand corner of the window. I guess I should clarify this and check if it's correct for win32/linux.

**Comment by bjz** [comment]
I reckon some documentation regarding glutin's coordinate system would be useful. Seeing as there are cross platform differences for high dpi displays, etc.

**Comment by bjz** [comment]
Ok, so those implementations are wrong, but I'll need to add some more methods to rust-cocoa to be able to fix it.

**Comment by bjz** [comment]
(ie. the position implementations)

**Comment by tomaka** [comment]
:shipit:

**Comment by tomaka** [comment]
I opened #223

**Comment by bjz** [comment]
Bad link?

**Pull request merged**
