### PR TITLE
Improvements to the headless api and separating out ffi bindings. New winit release. Style changes. Got rid of separated contexts in favour of raw contexts.

### PR DESCRIPTION
**Pull request by ZeGentzy**
#96

### CODE REVIEW

**Comment by ZeGentzy** [comment]
@mtak- @Osspial @mitchmindtree Can I get a confirmation this doesn't break ios, macos, windows or android. ([Going off the table here](https://github.com/tomaka/winit/blob/master/CONTRIBUTING.md))

More importantly, macos, because I removed `gl_bindings.rs` for it and android, cause I removed it's `ffi.rs`. They both appeared unused, but maybe they ought to be there for some reason unknown to me.

**Comment by Osspial** [comment]
Can confirm that this works on Windows.

**Comment by mickvangelderen** [comment]
I would like to know what the rationale behind separating out the ffi bindings is :)

**Comment by ZeGentzy** [comment]
@mickvangelderen 
It increases rebuild speed for glutin slightly. On my computer:
 - glutin v0.20: 0.93 to 1.1 seconds
 - glutin v0.19: 1.10 to 1.18 seconds

Tested via ten reruns of `touch {glutin,}/src/lib.rs && time cargo build`

Not much, I realize, but every little bit helps. Every file taken out of the main glutin crate is one less thing to recompile.

**Comment by ZeGentzy** [comment]
Release builds:
 - v0.20: 9.8 to 10.4
 - v0.19: 10.4 to 10.7

**Comment by mickvangelderen** [comment]
Would be good to know the time spent in glutin itself vs its dependencies.

**Comment by ZeGentzy** [comment]
@mickvangelderen I tried to think of ways I could easily bench that, but I can't think of any. Anyways, #1050 has some stats for user build times, which might interest you.

**Pull request merged**
